Port surfsession and surfbrowse to sh.

diff --git a/surfbrowse b/surfbrowse
--- a/surfbrowse
+++ b/surfbrowse
@@ -1,6 +1,6 @@
-#!/usr/bin/env rc
+#!/bin/sh
 
-# Manipulate `surf` via `dmenu`-based interface.
+# Manipulate `surf` via `sinmenu`-based interface.
 #
 # This script does:
 #
@@ -9,11 +9,11 @@
 #   * information debug, show all X properties on the `surf` window.
 #   * smart prefixes e.g. `g` for Google search, `t` for TinyURL, etc.
 #   * delete (with smart prefix `x`)
-#   * searching in page text (slightly broken)
+#   * history browsing, in conjunction with `surfsession`.
 #
 # Usage: `surfbrowse` _xid_ _action_
 #
-# _action_ must be one of `bookmark`, `go`, `go_raw`, `info`.
+# _action_ must be one of `bookmark`, `go`, `go_raw`, `info` or `history`
 #
 # To install, add the following to your `config.h`:
 #
@@ -26,129 +26,111 @@
 #     { GDK_SHIFT_MASK,                 GDK_i,      spawn,      BROWSE("info") },
 #     { GDK_CONTROL_MASK|GDK_SHIFT_MASK,GDK_g,      spawn,      BROWSE("go_raw") }
 #
-# The script uses sprop and a Plan 9 userland.  You may need to
-# uncomment the line below to get it to run (assuming your system sets
-# `$PLAN9` properly, just edit the path manually otherwise).
-#
-#     path=($PLAN9/bin $path)
-#
-# You also need [insitu][].
-#
-# Based on an `sh` shell script by Peter John Hartman, pancake, nibble and Peter John Hartman.
-#
-# [insitu]: http://sigkill.dk/programs/insitu
+# Based on a shell script by Peter John Hartman, pancake and nibble.
 
-SHELL=`{which rc}
+set -e # Die on error
 
 font='-*-terminus-medium-*-*-*-*-*-*-*-*-*-*-*'
 normbgcolor='#181818'
 normfgcolor='#e9e9e9'
-selbgcolor='#dd6003'
-selfgcolor='#e9e9e9'
-if (~ $#XDG_CACHE_HOME 0) {
-    surfcache=$home/.cache/surf
-}
-if not {
-    surfcache=$XDG_CACHE_HOME/surf
-}
+selbgcolor=$normbgcolor
+selfgcolor='#dd6003'
+
+surfcache=${XDG_CACHE_HOME:-~/.cache}/surf
 history=$surfcache/history
 visits=$surfcache/visits
 
 xid=$1
 p=$2
-dmenu=(dmenu -b -fn $font -nb $normbgcolor -nf $normfgcolor \
-       -sb $selbgcolor -sf $selfgcolor)
 
-fn escape { echo $1 | sed 's,[$^|?+*.()\[\]/],\\&,g' | sed 's/''/''''/g' | sed 's/#/\\#/g' }
-fn rmline {
-    grep -n $1 $2 | awk -F ':' '{print $1-NR+1"d"} END{print "w"}' | ed $2 > /dev/null
+menu="browserfield --nb $normbgcolor --nf $normfgcolor \
+       --sb $selbgcolor --sf $selfgcolor -l 10 -b"
+
+rawmenu="sinmenu --nb $normbgcolor --nf $normfgcolor \
+       --sb $selbgcolor --sf $selfgcolor -l 10 -b"
+echo $xid
+s_get_prop() { # xprop
+    xprop -id $xid $1 | cut -d '"' -f 2
 }
 
-fn s_get_prop { sprop $xid $1 | cut -d '''' -f 2 }
-
-fn s_set_prop { test -n $2 && sprop $xid $1 $2 }
-
-fn s_write_f {
-    if (test -n $2) {
-        tgt=`{escape $2}
-        insitu $1 'grep -v ''^'^$"tgt^'$'''
-        echo $2 >> $1
-    }
+s_set_prop() { # xprop value
+    [ -n "$2" ] && xprop -id $xid -f $1 8s -set $1 "$2"
 }
 
-fn s_set_write_proper_uri {
-    # input is whatever the use inputed, so don't store that!
-    # first, clear the name field because surf doesn't sometimes
-    s_set_prop WM_ICON_NAME ''
-    # set the uri
-    s_set_prop _SURF_GO $1
-    # get the new name
-    name=`{s_get_prop WM_ICON_NAME}
-    # loop until the [10%] stuff is finished and we have a load (is this necessary?)
-    while (echo $name | /bin/grep '[*%\]' >/dev/null >[2=1]) {
-        name=`{s_get_prop WM_ICON_NAME}
-    }
-    # bail on error and don't store
-    if (! ~ $name 'Error') {
-        uri=`{s_get_prop _SURF_URI}
-        # store to the history file the OFFICIAL url (with http://whatever)
-        s_write_f $history $1
-    }
+s_write_f() { # file value
+    [ -n "$2" ] && (sed -i "\|$2|d" $1; echo "$2" >> $1)
 }
 
-switch ($p) {
-    case info
-        xprop -id $xid | sed 's/	/    /g' | $dmenu -b -l 20
-    case bookmark
-        uri=`{s_get_prop _SURF_URI}
-        s_write_f $history $"uri
-    case go_raw
-        uri=`{echo `{s_get_prop _SURF_URI} | $dmenu -b -p 'uri:'}
-        s_set_prop _SURF_GO $"uri
-    case del
-        sel=`{tail -10000r $history >[2] /dev/null | $dmenu -b -l 5 -p 'uri [dgitwhy*]:'}
-        tgt=`{escape $"sel}
-        insitu $history 'grep -v ''^'^$"tgt^'$'''
-    case history
-        sel=`{tail -10000r $visits >[2] /dev/null | $dmenu -b -l 5 -p 'uri from history:' | awk -F' - ' '{print $1}' }
-        s_set_prop _SURF_GO $"sel
-    case go
-        sel=`{tail -10000r $history >[2] /dev/null | $dmenu -b -l 5 -p 'uri [dgitwhy*]:'}
-        test -z $"sel && exit
-        opt=`{echo $sel | cut -d ' ' -f 1}
-        arg=`{echo $sel | cut -d ' ' -f 2-}
+s_set_write_proper_uri() { # uri
+    s_set_prop WM_ICON_NAME '' || true
+    s_set_prop _SURF_GO "$1"
+    s_write_f $history "$1"
+}
+
+case "$p" in
+    info)
+        xprop -id $xid | sed 's/\t/    /g' | $rawmenu -l 20
+        ;;
+    bookmark)
+        uri=$(s_get_prop _SURF_URI)
+        s_write_f $history "$uri"
+        ;;
+    del)
+        sel=$(tac $history 2>/dev/null | $menu -p 'uri [dgitwhy*]:')
+        sed -i "\|$sel|d" $history
+        ;;
+    history)
+        sel=$(tac $visits 2>/dev/null | $rawmenu -p 'uri from history:' | awk -F' - ' '{print $1}')
+        s_set_prop _SURF_GO "$sel"
+        ;;
+    go_raw)
+        uri=$(echo $(s_get_prop _SURF_URI) | $menu -p "uri:")
+        s_set_prop _SURF_GO "$uri"
+        ;;
+    go)
+        sel=$(tac $history 2> /dev/null | $menu -p "uri [dgtwuy*]:")
+        [ -z "$sel" ] && exit
+        opt=$(echo $sel | cut -d ' ' -f 1)
+        arg=$(echo $sel | cut -d ' ' -f 2-)
         save=0
-        switch ($opt) {
-            case d # del.icio.us
-                uri='http://del.icio.us/save?url='^`{s_get_prop _SURF_URI}
-            case g # google for it
-                uri='http://www.google.com/search?q='^$"arg
+        case "$opt" in
+            "g")
+                uri="http://www.google.com/search?q=$arg"
                 save=1
-            case i # google for it as image
-                uri='http://www.google.com/images?q='^$"arg
+                ;;
+            "i")
+                uri="http://www.google.com/images?q=$arg"
                 save=1
-            case t # tinyurl
-                uri='http://tinyurl.com/create.php?url='^`{s_get_prop _SURF_URI}
-            case w # wikipedia
-                uri='http://wikipedia.org/wiki/'^$"arg
+                ;;
+            "t")
+                uri="http://tinyurl.com/create.php?url=`s_get_prop _SURF_URI`"
+                ;;
+            "w")
+                uri="http://wikipedia.org/wiki/$arg"
                 save=1
-            case h
-                uri='http://holumbus.fh-wedel.de/hayoo/hayoo.html?query='$"arg'&start'
-                #uri='http://haskell.org/hoogle/?q='^$"arg
+                ;;
+            "h")
+                uri="http://haskell.org/hoogle/?q=$arg"
                 save=1
-            case y # youtube
-                uri='http://www.youtube.com/results?search_query='^$"arg^'&aq=f'
+                ;;
+            "y")
+                uri="http://www.youtube.com/results?search_query=$arg&aq=f"
                 save=1
-            case *
-                uri=$"sel
+                ;;
+            *)
+                uri="$sel"
                 save=2
-        }
-        # only set the uri; don't write to file
-        if (~ $save 0) s_set_prop _SURF_GO $uri
-        # set the url and write exactly what the user inputed to the file
-        if (~ $save 1) {s_set_prop _SURF_GO $uri; s_write_f $history $"sel}
-        # try to set the uri only if it is a success
-        if (~ $save 2) s_set_write_proper_uri $uri
-    case *
-         echo Unknown action $p
-}
+                ;;
+        esac
+
+    # only set the uri; don't write to file
+        [ $save -eq 0 ] && s_set_prop _SURF_GO "$uri"
+    # set the url and write exactly what the user inputed to the file
+        [ $save -eq 1 ] && (s_set_prop _SURF_GO "$uri"; s_write_f $history "$sel")
+    # try to set the uri only if it is a success
+        [ $save -eq 2 ] && s_set_write_proper_uri "$uri"
+        ;;
+    *)
+        echo Unknown xprop
+        ;;
+esac
diff --git a/surfsession b/surfsession
--- a/surfsession
+++ b/surfsession
@@ -1,4 +1,4 @@
-#!/usr/bin/env rc
+#!/bin/sh
 
 # Simplistic session management for `surf`.
 #
@@ -6,7 +6,7 @@
 # history is stored.  The script is supposed to be called
 # automatically by `surf` to update URL data, and by user commands to
 # resume them.  File locking via `flock` is used to ensure atomicity
-# of modifications to `.surf/sessions`.
+# of modifications to the sessions file.
 #
 # An URL is considered an "orphan" if its listed PID no longer
 # refers to a live process.
@@ -23,91 +23,66 @@
 #
 # * `restore`: start `surf` for all orphan URLs.
 #
-# * `resume`: use `dmenu` to select an orphan URL, which will be
+# * `resume`: use `sinmenu` to select an orphan URL, which will be
 #   opened in `surf`.
-#
-# The script uses sprop and a Plan 9 userland.  You may need to
-# uncomment the line below to get it to run (assuming your system sets
-# `$PLAN9` properly, just edit the path manually otherwise).
-#
-#     path=($PLAN9/bin $path)
-#
-# You also need [insitu][].
-#
-# [insitu]: http://sigkill.dk/programs/insitu
 
-flag +e # Die on error
+set -e # Die on error
 
-SHELL=`{which rc}
-
-# dmenu setup shamelessly cribbed from surf.sh.
 font='-*-terminus-medium-*-*-*-*-*-*-*-*-*-*-*'
 normbgcolor='#181818'
 normfgcolor='#e9e9e9'
 selbgcolor='#dd6003'
 selfgcolor='#e9e9e9'
-dmenu=(dmenu -fn $font -nb $normbgcolor -nf $normfgcolor \
-       -sb $selbgcolor -sf $selfgcolor -l 10 -b)
+menu="sinmenu --nb $normbgcolor --nf $normfgcolor \
+      --sb $selbgcolor --sf $selfgcolor -l 10"
 
-fn escape { echo $1 | sed 's,[$^|?+*.()\[\]],\\&,g' | sed 's/''/''''/g' }
-
-fn orphans {
-   awk '{ if (system("test -d /proc/"$1)) { print(substr($0,index($0,$2))) }}' $sessions
+orphans () {
+    awk '{ if (system("test -d /proc/"$1)) { print(substr($0,index($0,$2))) }}' $sessions
 }
 
-fn rmtitle {
-   awk '{print substr($0,0,index($0," - "))}'
+rmtitle () {
+    awk '{print substr($0,1,index($0," - "))}'
 }
 
 visitssize=500000
 
-if (~ $#XDG_CACHE_HOME 0) {
-    surfcache=$home/.cache/surf
-}
-if not {
-    surfcache=$XDG_CACHE_HOME/surf
-}
-
+surfcache=${XDG_CACHE_HOME:-~/.cache}/surf
 sessions=$surfcache/sessions
 visits=$surfcache/visits
-if (touch $sessions) {
+
+if touch $sessions; then
    # We translate command foo to foo-locked surrounded by locking of
    # $surfcache.
-   switch ($1) {
-       case add-locked
-          tgt=`{escape $3}
-          insitu $visits 'grep -v '''$tgt'''|tail -n '$visitssize
-          echo $3 ' - ' $4  >> $visits
-          echo $2 $3 ' - ' $4 >> $sessions
-       case remove-locked
-          insitu $sessions 'grep -v ''^'^$2^' '^`{escape $3}^'$'''
-       case purge-locked
-          insitu $sessions 'grep -v ''^[0-9]+ '^`{escape $2}^'$'''
-       case restore-locked
-          {
-                orphans | rmtitle | { url=`{read}; surf $"url & }
-          }
-          rm $sessions
-       case resume-locked
-           ifs='
-' res=`{orphans|$dmenu|rmtitle}
-           if (! ~ $status '') exit 1
-           $0 purge-locked $res && surf $res &
-       # Don't deadlock on unknown commands...
-       case *-locked
-          exit 1
-       # Wrap a command in file locking and rerun the script.
-       case *
-          cmd=$1-locked
-          shift
-          args=`{for (arg in $*) {
-                     varg=`{echo $arg|sed 's/''/''''/g'}
-                     echo ''''^$"varg^''''
-                }} # quote for subshell...
-          flock -o $surfcache -c $0^' '^$cmd^' '^$"args
-   }
-}
-if not {
-    echo 'Cannot write to '$surfcache >[1=2]
+    case "$1" in
+        add-locked)
+            (rm "$visits" && tail -n $visitssize | awk 'index($0, URL" - ")!=1' "URL=$3" > "$visits") < "$visits"
+            $0 remove-locked "$2"
+            echo "$3 - $4" >> "$visits"
+            echo "$2 $3 - $4" >> "$sessions"
+            ;;
+        remove-locked)
+            (rm "$sessions" && awk '$1!=PID' "PID=$2" > "$sessions") < "$sessions"
+            ;;
+        purge-locked)
+            (rm "$sessions" && awk '$2!=URL' "URL=$2" > "$sessions") < "$sessions"
+            ;;
+        restore-locked)
+            orphans | rmtitle | ( url=$(read); surf "$url" & )
+            rm $sessions
+            ;;
+        resume-locked)
+            res=$(orphans|$menu|rmtitle)
+            [ -n "$res" ] && $0 purge-locked $res && surf $res &
+            ;;
+        *-locked) # Don't deadlock on unknown commands...
+            exit 1
+            ;;
+        *) # Wrap a command in file locking and rerun the script.
+            cmd=$1-locked
+            shift
+            flock -o $surfcache $0 "$cmd" "$@"
+    esac
+else
+    echo 'Cannot write to '$surfcache 1>&2
     exit 1
-}
+fi
